//CART TYPES
export const ADD_ITEM = "ADD_ITEM";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CLEAR_CART = "CLEAR_CART";

// FETCH COLLECTION
export const FETCH_COLLECTION = "FETCH_COLLECTION";
